### ISSUE TITLE
Card names missing

### ISSUE THREAD

**Issue by ScorpioneOrzion** [benediktwerner/Stacklands-GolemAutomation-Mod#1]
Maybe its usefull if they are named...

**Comment by ScorpioneOrzion** [comment]
Nevermind this is not the situation when playing in English.

**Comment by benediktwerner** [comment]
Hm, I didn't think the game would still load English first even if you have another language selected so it didn't insert the terms correctly. Should now work with other languages as well if you update to the latest version.
